import {
  BusinessSettings,
  Customer,
  Expense,
  Invoice,
  Order,
  Payment,
  ProductService,
  Quotation,
} from '../types';

export const INITIAL_SETTINGS: BusinessSettings = {
  businessName: 'NISSI KREATIONS',
  tagline: 'Flex, Vinyl, Signboards, Offset & Digital Printing Studio',
  logoUrl: '', // uses vector/embedded brand logo when empty or custom dataURL
  phone: '+91 98480 12345',
  alternatePhone: '+91 98480 67890',
  email: 'info.nissikreations@gmail.com',
  website: 'www.nissikreations.com',
  addressLine1: '#12-4-88, Plot 14, Commercial Complex, Metro Pillar 45',
  addressLine2: 'Main Road, Ameerpet',
  city: 'Hyderabad',
  state: 'Telangana',
  pincode: '500016',
  gstNumber: '36AAECN4589K1Z5',
  panNumber: 'AAECN4589K',
  upiId: 'nissikreations@okhdfcbank',
  upiQrCodeUrl: '',
  bankName: 'HDFC Bank',
  bankAccountName: 'NISSI KREATIONS',
  accountNumber: '50200098480123',
  ifscCode: 'HDFC0000452',
  branchName: 'Ameerpet Branch',
  invoicePrefix: 'NK-INV-',
  quotationPrefix: 'NK-QTN-',
  receiptPrefix: 'NK-REC-',
  orderPrefix: 'NK-ORD-',
  currencySymbol: '₹',
  defaultGstRate: 18,
  defaultTerms: `1. 50% advance payment required upon order confirmation.
2. Balance payment must be settled upon or prior to delivery.
3. Final proof approval is the customer's responsibility. Once approved, printing cannot be cancelled.
4. Color reproduction may vary slightly (5-10%) based on substrate material.
5. All disputes are subject to local city jurisdiction.`,
  customExpenseCategories: [
    'Flex Material',
    'Vinyl',
    'Printing Material',
    'Ink',
    'Paper',
    'Design',
    'Electricity',
    'Rent',
    'Transport',
    'Labour',
    'Maintenance',
    'Advertising',
    'Packaging',
    'Office Expenses',
    'Other',
  ],
};

export const INITIAL_PRODUCTS: ProductService[] = [
  {
    id: 'prod-1',
    name: 'Star Flex Banner (Frontlit)',
    category: 'Flex Printing',
    description: 'High-grade 340 GSM Star flex banner with eyelets & border stitching',
    unit: 'sq.ft',
    defaultRate: 14,
    defaultTaxPercent: 18,
    isActive: true,
  },
  {
    id: 'prod-2',
    name: 'Blackout Backlit Flex Banner',
    category: 'Flex Printing',
    description: 'Premium light-box backlit flex 510 GSM for glowing glow-signs',
    unit: 'sq.ft',
    defaultRate: 35,
    defaultTaxPercent: 18,
    isActive: true,
  },
  {
    id: 'prod-3',
    name: 'Vinyl Printing + Gloss/Matt Lamination',
    category: 'Vinyl Printing',
    description: 'High-resolution eco-solvent self-adhesive vinyl with protective lamination',
    unit: 'sq.ft',
    defaultRate: 45,
    defaultTaxPercent: 18,
    isActive: true,
  },
  {
    id: 'prod-4',
    name: 'Sunboard 3mm Mount + Vinyl Print',
    category: 'Sunboard',
    description: 'Direct mounting of laminated vinyl on 3mm rigid PVC sunboard',
    unit: 'sq.ft',
    defaultRate: 75,
    defaultTaxPercent: 18,
    isActive: true,
  },
  {
    id: 'prod-5',
    name: 'One-Way Vision Glass Film',
    category: 'Glass Branding',
    description: 'Perforated one-way window graphics for storefronts & vehicle glasses',
    unit: 'sq.ft',
    defaultRate: 65,
    defaultTaxPercent: 18,
    isActive: true,
  },
  {
    id: 'prod-6',
    name: 'Premium Visiting Cards (350 GSM Velvet/Matt)',
    category: 'Stationery',
    description: 'Double-sided multi-color visiting cards with thermal velvet finish (Box of 1000)',
    unit: 'sets',
    defaultRate: 850,
    defaultTaxPercent: 12,
    isActive: true,
  },
  {
    id: 'prod-7',
    name: 'Custom Die-Cut Vinyl Stickers',
    category: 'Stickers',
    description: 'Waterproof round/custom contour die-cut label stickers',
    unit: 'pcs',
    defaultRate: 3.5,
    defaultTaxPercent: 18,
    isActive: true,
  },
  {
    id: 'prod-8',
    name: 'Roll-up Standee (3x6 ft) Complete Set',
    category: 'Display Stands',
    description: 'Aluminium cassette standee with non-tearable star flex print & carry bag',
    unit: 'pcs',
    defaultRate: 1450,
    defaultTaxPercent: 18,
    isActive: true,
  },
  {
    id: 'prod-9',
    name: 'Graphic Design & Vector Artworking',
    category: 'Design Services',
    description: 'Professional creative layout, typography, logo vectorization & ready-to-print file',
    unit: 'hours',
    defaultRate: 500,
    defaultTaxPercent: 18,
    isActive: true,
  },
  {
    id: 'prod-10',
    name: 'On-Site Signboard Installation Charges',
    category: 'Installation',
    description: 'Mounting, iron frame alignment, scaffolding & electrical fittings',
    unit: 'pcs',
    defaultRate: 1200,
    defaultTaxPercent: 18,
    isActive: true,
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Apex Supermarket & Stores',
    phone: '9849123456',
    email: 'purchase@apexsupermarket.com',
    address: 'Shop 101, Horizon Mall, Road No. 36, Jubilee Hills, Hyderabad',
    gstNumber: '36AAACP9876Q1Z3',
    notes: 'Regular client for monthly promotional flex banners & floor decals',
    createdAt: '2026-07-10T10:00:00.000Z',
    updatedAt: '2026-08-12T14:30:00.000Z',
  },
  {
    id: 'cust-2',
    name: 'Dr. Srinivas Wellness Clinic',
    phone: '9988776655',
    email: 'dr.srinivas@wellnessclinic.in',
    address: 'Plot 45, Gachibowli Main Road, Hyderabad',
    gstNumber: '36BBDPS1234R1Z8',
    notes: 'Reception acrylic 3D letters and window one-way vision graphics',
    createdAt: '2026-07-22T11:20:00.000Z',
    updatedAt: '2026-08-14T09:15:00.000Z',
  },
  {
    id: 'cust-3',
    name: 'Spice Garden Multi-Cuisine Restaurant',
    phone: '9700112233',
    email: 'contact@spicegardenhyd.com',
    address: 'Opp. Cyber Gateway, Hitech City, Madhapur, Hyderabad',
    gstNumber: '36CCXPS5678S1Z1',
    notes: 'Menu boards, LED backlit board, menu cards and standees',
    createdAt: '2026-08-01T15:45:00.000Z',
    updatedAt: '2026-08-15T18:00:00.000Z',
  },
  {
    id: 'cust-4',
    name: 'Royal Heritage Real Estate Developers',
    phone: '9848055443',
    email: 'marketing@royalheritageinfra.com',
    address: 'Level 5, Capital Towers, Financial District, Nanakramguda, Hyderabad',
    gstNumber: '36DDEPK4321T1Z9',
    notes: 'Large hoarding prints, site perimeter hoardings, brochures',
    createdAt: '2026-08-05T09:30:00.000Z',
    updatedAt: '2026-08-16T11:00:00.000Z',
  },
];

export const INITIAL_QUOTATIONS: Quotation[] = [
  {
    id: 'qtn-1',
    quotationNumber: 'NK-QTN-0001',
    date: '2026-08-14',
    validUntil: '2026-08-28',
    customerId: 'cust-4',
    customerName: 'Royal Heritage Real Estate Developers',
    customerPhone: '9848055443',
    customerEmail: 'marketing@royalheritageinfra.com',
    customerAddress: 'Level 5, Capital Towers, Financial District, Nanakramguda, Hyderabad',
    customerGstNumber: '36DDEPK4321T1Z9',
    items: [
      {
        id: 'item-q1-1',
        description: 'Large Site Hoarding Flex Print (Star 340 GSM)',
        width: 40,
        height: 20,
        quantity: 2,
        unit: 'sq.ft',
        rate: 14,
        discount: 5,
        taxPercent: 18,
        total: 25118.4,
      },
      {
        id: 'item-q1-2',
        description: 'Roll-up Standee (3x6 ft) with Carry Bag',
        quantity: 4,
        unit: 'pcs',
        rate: 1450,
        discount: 0,
        taxPercent: 18,
        total: 6844,
      },
      {
        id: 'item-q1-3',
        description: 'High-Resolution Graphic Design & Layout Master File',
        quantity: 2,
        unit: 'hours',
        rate: 500,
        discount: 0,
        taxPercent: 18,
        total: 1180,
      },
    ],
    subtotal: 29200,
    discountTotal: 1120,
    taxTotal: 5054.4,
    grandTotal: 33142.4,
    status: 'Sent',
    notes: 'Quotation includes reinforced eyelets and edge welding for wind resistance.',
    termsAndConditions: INITIAL_SETTINGS.defaultTerms,
    createdAt: '2026-08-14T10:30:00.000Z',
    updatedAt: '2026-08-14T10:30:00.000Z',
  },
  {
    id: 'qtn-2',
    quotationNumber: 'NK-QTN-0002',
    date: '2026-08-15',
    validUntil: '2026-08-30',
    customerId: 'cust-1',
    customerName: 'Apex Supermarket & Stores',
    customerPhone: '9849123456',
    customerEmail: 'purchase@apexsupermarket.com',
    customerAddress: 'Shop 101, Horizon Mall, Road No. 36, Jubilee Hills, Hyderabad',
    customerGstNumber: '36AAACP9876Q1Z3',
    items: [
      {
        id: 'item-q2-1',
        description: 'Festival Sale Outdoor Frontlit Flex Banner',
        width: 20,
        height: 8,
        quantity: 3,
        unit: 'sq.ft',
        rate: 14,
        discount: 0,
        taxPercent: 18,
        total: 7929.6,
      },
      {
        id: 'item-q2-2',
        description: 'Laminated Floor Promotional Vinyl Graphics',
        width: 4,
        height: 2,
        quantity: 10,
        unit: 'sq.ft',
        rate: 45,
        discount: 0,
        taxPercent: 18,
        total: 4248,
      },
    ],
    subtotal: 10320,
    discountTotal: 0,
    taxTotal: 1857.6,
    grandTotal: 12177.6,
    status: 'Accepted',
    notes: 'Approved via email on Aug 15. Proceeding with order production.',
    termsAndConditions: INITIAL_SETTINGS.defaultTerms,
    createdAt: '2026-08-15T09:00:00.000Z',
    updatedAt: '2026-08-15T14:20:00.000Z',
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-1',
    invoiceNumber: 'NK-INV-0001',
    quotationNumber: 'NK-QTN-0000',
    orderNumber: 'NK-ORD-0001',
    date: '2026-08-10',
    dueDate: '2026-08-20',
    customerId: 'cust-3',
    customerName: 'Spice Garden Multi-Cuisine Restaurant',
    customerPhone: '9700112233',
    customerEmail: 'contact@spicegardenhyd.com',
    customerAddress: 'Opp. Cyber Gateway, Hitech City, Madhapur, Hyderabad',
    customerGstNumber: '36CCXPS5678S1Z1',
    items: [
      {
        id: 'item-inv1-1',
        description: 'Backlit Glow Signboard Flex Print',
        width: 15,
        height: 4,
        quantity: 1,
        unit: 'sq.ft',
        rate: 35,
        discount: 0,
        taxPercent: 18,
        total: 2478,
      },
      {
        id: 'item-inv1-2',
        description: 'Sunboard 3mm Menu Boards with Matt Lamination',
        width: 3,
        height: 2,
        quantity: 6,
        unit: 'sq.ft',
        rate: 75,
        discount: 5,
        taxPercent: 18,
        total: 3026.7,
      },
      {
        id: 'item-inv1-3',
        description: 'Installation & Electrical Wiring of Glow Sign',
        quantity: 1,
        unit: 'pcs',
        rate: 1200,
        discount: 0,
        taxPercent: 18,
        total: 1416,
      },
    ],
    subtotal: 6000,
    discountTotal: 135,
    taxTotal: 1055.7,
    grandTotal: 6920.7,
    amountPaid: 6920.7,
    balanceDue: 0,
    status: 'Paid',
    notes: 'Thank you for your business! Fully cleared via UPI.',
    termsAndConditions: INITIAL_SETTINGS.defaultTerms,
    createdAt: '2026-08-10T12:00:00.000Z',
    updatedAt: '2026-08-11T16:00:00.000Z',
  },
  {
    id: 'inv-2',
    invoiceNumber: 'NK-INV-0002',
    orderNumber: 'NK-ORD-0002',
    date: '2026-08-14',
    dueDate: '2026-08-24',
    customerId: 'cust-2',
    customerName: 'Dr. Srinivas Wellness Clinic',
    customerPhone: '9988776655',
    customerEmail: 'dr.srinivas@wellnessclinic.in',
    customerAddress: 'Plot 45, Gachibowli Main Road, Hyderabad',
    customerGstNumber: '36BBDPS1234R1Z8',
    items: [
      {
        id: 'item-inv2-1',
        description: 'One-Way Vision Perforated Glass Film Printing',
        width: 12,
        height: 6,
        quantity: 2,
        unit: 'sq.ft',
        rate: 65,
        discount: 0,
        taxPercent: 18,
        total: 11044.8,
      },
      {
        id: 'item-inv2-2',
        description: 'Premium Velvet Visiting Cards (Double Sided - 1000 cards)',
        quantity: 2,
        unit: 'sets',
        rate: 850,
        discount: 0,
        taxPercent: 12,
        total: 1904,
      },
    ],
    subtotal: 11060,
    discountTotal: 0,
    taxTotal: 1888.8,
    grandTotal: 12948.8,
    amountPaid: 6500,
    balanceDue: 6448.8,
    status: 'Partially Paid',
    notes: 'Advance of ₹6,500 received via Bank Transfer. Remaining due on completion.',
    termsAndConditions: INITIAL_SETTINGS.defaultTerms,
    createdAt: '2026-08-14T15:30:00.000Z',
    updatedAt: '2026-08-14T17:00:00.000Z',
  },
  {
    id: 'inv-3',
    invoiceNumber: 'NK-INV-0003',
    date: '2026-08-16',
    dueDate: '2026-08-26',
    customerId: 'cust-1',
    customerName: 'Apex Supermarket & Stores',
    customerPhone: '9849123456',
    customerEmail: 'purchase@apexsupermarket.com',
    customerAddress: 'Shop 101, Horizon Mall, Road No. 36, Jubilee Hills, Hyderabad',
    customerGstNumber: '36AAACP9876Q1Z3',
    items: [
      {
        id: 'item-inv3-1',
        description: 'Festival Sale Outdoor Frontlit Flex Banner (20x8 ft)',
        width: 20,
        height: 8,
        quantity: 3,
        unit: 'sq.ft',
        rate: 14,
        discount: 0,
        taxPercent: 18,
        total: 7929.6,
      },
      {
        id: 'item-inv3-2',
        description: 'Laminated Floor Promotional Vinyl Graphics',
        width: 4,
        height: 2,
        quantity: 10,
        unit: 'sq.ft',
        rate: 45,
        discount: 0,
        taxPercent: 18,
        total: 4248,
      },
    ],
    subtotal: 10320,
    discountTotal: 0,
    taxTotal: 1857.6,
    grandTotal: 12177.6,
    amountPaid: 0,
    balanceDue: 12177.6,
    status: 'Unpaid',
    notes: 'Generated from accepted Quotation NK-QTN-0002. Delivery scheduled for Aug 18.',
    termsAndConditions: INITIAL_SETTINGS.defaultTerms,
    createdAt: '2026-08-16T11:00:00.000Z',
    updatedAt: '2026-08-16T11:00:00.000Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1',
    orderNumber: 'NK-ORD-0001',
    customerId: 'cust-3',
    customerName: 'Spice Garden Multi-Cuisine Restaurant',
    customerPhone: '9700112233',
    orderDate: '2026-08-08',
    deliveryDate: '2026-08-11',
    description: 'Backlit glow signboard (15x4 ft) & 6 Sunboard menu boards',
    dimensions: '15x4 ft + 3x2 ft (6 nos)',
    quantity: 7,
    amount: 6920.7,
    advancePaid: 6920.7,
    balance: 0,
    status: 'Delivered',
    notes: 'Delivered and installed on site successfully.',
    invoiceId: 'inv-1',
    createdAt: '2026-08-08T10:00:00.000Z',
    updatedAt: '2026-08-11T16:30:00.000Z',
  },
  {
    id: 'ord-2',
    orderNumber: 'NK-ORD-0002',
    customerId: 'cust-2',
    customerName: 'Dr. Srinivas Wellness Clinic',
    customerPhone: '9988776655',
    orderDate: '2026-08-14',
    deliveryDate: '2026-08-17',
    description: 'One-Way Vision Glass Graphics & 2000 Velvet Visiting Cards',
    dimensions: '12x6 ft (2 nos) + Cards',
    quantity: 4,
    amount: 12948.8,
    advancePaid: 6500,
    balance: 6448.8,
    status: 'Printing',
    notes: 'Film printed, curing in rack. Visiting cards on offset press.',
    invoiceId: 'inv-2',
    createdAt: '2026-08-14T14:00:00.000Z',
    updatedAt: '2026-08-16T09:30:00.000Z',
  },
  {
    id: 'ord-3',
    orderNumber: 'NK-ORD-0003',
    customerId: 'cust-1',
    customerName: 'Apex Supermarket & Stores',
    customerPhone: '9849123456',
    orderDate: '2026-08-16',
    deliveryDate: '2026-08-18',
    description: '3 Frontlit Star Banners (20x8 ft) & 10 Floor Vinyl decals',
    dimensions: '20x8 ft (3) + 4x2 ft (10)',
    quantity: 13,
    amount: 12177.6,
    advancePaid: 0,
    balance: 12177.6,
    status: 'Designing',
    notes: 'Artworking sent to client for high-res logo confirmation.',
    invoiceId: 'inv-3',
    createdAt: '2026-08-16T11:15:00.000Z',
    updatedAt: '2026-08-16T11:15:00.000Z',
  },
  {
    id: 'ord-4',
    orderNumber: 'NK-ORD-0004',
    customerId: 'cust-4',
    customerName: 'Royal Heritage Real Estate Developers',
    customerPhone: '9848055443',
    orderDate: '2026-08-16',
    deliveryDate: '2026-08-22',
    description: '40x20 ft Site perimeter hoarding flex banners (2 pcs)',
    dimensions: '40x20 ft (2 pcs)',
    quantity: 2,
    amount: 25118.4,
    advancePaid: 10000,
    balance: 15118.4,
    status: 'Confirmed',
    notes: 'Received advance token. Awaiting scaffolding readiness on site.',
    quotationId: 'qtn-1',
    createdAt: '2026-08-16T16:00:00.000Z',
    updatedAt: '2026-08-16T16:00:00.000Z',
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay-1',
    paymentNumber: 'NK-REC-0001',
    date: '2026-08-11',
    customerId: 'cust-3',
    customerName: 'Spice Garden Multi-Cuisine Restaurant',
    invoiceId: 'inv-1',
    invoiceNumber: 'NK-INV-0001',
    amount: 6920.7,
    paymentMethod: 'UPI',
    referenceNumber: 'UPI/322409817621',
    notes: 'Full invoice amount settled at delivery time.',
    remainingBalanceAfter: 0,
    createdAt: '2026-08-11T16:00:00.000Z',
  },
  {
    id: 'pay-2',
    paymentNumber: 'NK-REC-0002',
    date: '2026-08-14',
    customerId: 'cust-2',
    customerName: 'Dr. Srinivas Wellness Clinic',
    invoiceId: 'inv-2',
    invoiceNumber: 'NK-INV-0002',
    amount: 6500,
    paymentMethod: 'Bank Transfer',
    referenceNumber: 'NEFT-N22824009187',
    notes: '50% advance token for window graphics and visiting cards order.',
    remainingBalanceAfter: 6448.8,
    createdAt: '2026-08-14T17:00:00.000Z',
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    date: '2026-08-09',
    category: 'Flex Material',
    description: 'Star Flex Rolls (10 ft width x 50 meter rolls, 2 units)',
    amount: 5400,
    paymentMethod: 'UPI',
    referenceNumber: 'TXN-998811',
    vendorName: 'Sri Balaji Flex Media Wholesale',
    notes: 'Stock purchase for monthly print requirements',
    createdAt: '2026-08-09T11:00:00.000Z',
  },
  {
    id: 'exp-2',
    date: '2026-08-10',
    category: 'Ink',
    description: 'Eco-Solvent CMYK Ink Set (4 x 1 Litre bottles)',
    amount: 3200,
    paymentMethod: 'Bank Transfer',
    referenceNumber: 'NEFT-INK-7761',
    vendorName: 'ColorTech Inks Hyderabad',
    notes: 'High-density Konica head solvent ink bottles',
    createdAt: '2026-08-10T14:30:00.000Z',
  },
  {
    id: 'exp-3',
    date: '2026-08-12',
    category: 'Electricity',
    description: 'Commercial Power bill for printing workshop (July billing)',
    amount: 4150,
    paymentMethod: 'UPI',
    referenceNumber: 'TSSPDCL-99281',
    vendorName: 'TSSPDCL Southern Power',
    notes: 'Workshop 3-phase connection',
    createdAt: '2026-08-12T10:15:00.000Z',
  },
  {
    id: 'exp-4',
    date: '2026-08-14',
    category: 'Vinyl',
    description: 'LG Premium Self-Adhesive Vinyl 4.5 ft roll with Gloss Lamination',
    amount: 2850,
    paymentMethod: 'Cash',
    referenceNumber: '',
    vendorName: 'Sanjay Graphic Supplies',
    notes: 'For clinic one-way and gloss stickers',
    createdAt: '2026-08-14T11:00:00.000Z',
  },
  {
    id: 'exp-5',
    date: '2026-08-16',
    category: 'Labour',
    description: 'Operator weekly overtime & mounting helper daily wages',
    amount: 1500,
    paymentMethod: 'Cash',
    referenceNumber: '',
    vendorName: 'Workshop Staff',
    notes: 'Weekend night printing shift assistance',
    createdAt: '2026-08-16T18:00:00.000Z',
  },
];
